# Exploración de las bases de la ENGHo

En este notebook voy a explorar la ENGHo de manera descriptiva. Son descargables desde (la página del INDEC)[https://www.indec.gob.ar/indec/web/Institucional-Indec-BasesDeDatos-4].

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Carga de datos
### Carga de la base hogares `engho2018_hogares.txt`

In [2]:
hogares_df = pd.read_csv(
    "../data/engho2018_hogares.txt",
    sep="|",
    decimal=".",
    quotechar="\""
)
hogares_df.info()
hogares_df.tail()

<class 'pandas.DataFrame'>
RangeIndex: 21547 entries, 0 to 21546
Columns: 134 entries, id to dinpch_t
dtypes: float64(64), int64(69), str(1)
memory usage: 22.0 MB

,id,provincia,region,subregion,trimestre,anio,pondera,cv1c04,cv1c05_a,cv1c05_b,...,qinth_t,dinth_p,dinth_r,dinth_t,qinpch_p,qinpch_r,qinpch_t,dinpch_p,dinpch_r,dinpch_t
21542,57618153,94,6,6B,3,2018,124,1,3.0,2.0,...,3,2,4,5,4,5,5,7,9,9
21543,551737923,94,6,6B,3,2018,123,1,3.0,2.0,...,4,4,7,8,5,5,5,10,10,10
21544,188896348,94,6,6B,1,2018,11,1,2.0,2.0,...,1,1,2,2,1,1,1,1,2,2
21545,127611813,94,6,6B,2,2018,68,1,3.0,3.0,...,5,9,10,10,4,5,5,8,9,10
21546,37138480,94,6,6B,2,2018,59,1,3.0,3.0,...,5,7,9,9,3,4,5,6,8,9

In [3]:
hogares_cols = [
    "id",           # Clave de identificación del hogar
    "pondera",      # Factor de expansión
    "jniveled",     # Nivel educativo del jefe o la jefa del hogar
    "jocupengh",    # Categoría ocupacional del jefe o la jefa del hogar
    "cantmiem",     # Tamaño del hogar
    "cv1c04",       # Tipo de vivienda
    "cantping",     # Cantidad de perceptores de ingreso
    "reldep",       # Cantidad de miembros por cada miembro perceptor de ingresos
    "regten",       # Régimen de tenencia de la vivienda
    "gastot",       # Gasto de consumo total del hogar
    "gc_01",        # Alimentos y bebidas no alcohólicas
    "gc_02",        # Bebidas alcohólicas y tabaco
    "gc_03",        # Prendas de vestir y calzado
    "gc_04",        # Vivienda, agua, electricidad, gas y otros combustibles
    "gc_05",        # Equipamiento y mantenimiento del hogar
    "gc_06",        # Salud
    "gc_07",        # Transporte
    "gc_08",        # Comunicaciones
    "gc_09",        # Recreación y cultura
    "gc_10",        # Educación
    "gc_11",        # Restaurantes y hoteles
    "gc_12",        # Bienes y servicios varios
    "ingtoth",      # Ingreso total del hogar
    "decgaphr",     # Decil de gasto de consumo per cápita del hogar. Región
    "decgapht",     # Decil de gasto de consumo per cápita del hogar. Total del país
    "hacina",       # Cantidad de miembros por habitación de uso exclusivo
    "ch07",         # Servicios Públicos: Electricidad
    "ch09",         # Servicios Públicos: Agua
    "ch14",         # Servicios Públicos: Cloaca
    "ch15",         # Servicios Públicos: Gas
    "ch21",         # Hogar con aire acondicionado
    "regten",       # Régimen de tenencia de la vivienda
    "propauto"      # Hogar propietario de automóvil
]

In [4]:
hog = hogares_df[hogares_cols].copy()
hog.info()

<class 'pandas.DataFrame'>
RangeIndex: 21547 entries, 0 to 21546
Data columns (total 33 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         21547 non-null  int64
 1   pondera    21547 non-null  int64
 2   jniveled   21547 non-null  int64
 3   jocupengh  13956 non-null  float64
 4   cantmiem   21547 non-null  int64
 5   cv1c04     21547 non-null  int64
 6   cantping   21547 non-null  int64
 7   reldep     21530 non-null  float64
 8   regten     21547 non-null  int64
 9   gastot     21547 non-null  float64
 10  gc_01      21547 non-null  float64
 11  gc_02      21547 non-null  float64
 12  gc_03      21547 non-null  float64
 13  gc_04      21547 non-null  float64
 14  gc_05      21547 non-null  float64
 15  gc_06      21547 non-null  float64
 16  gc_07      21547 non-null  float64
 17  gc_08      21547 non-null  float64
 18  gc_09      21547 non-null  float64
 19  gc_10      21547 non-null  float64
 20  gc_11      21547 non-null  float64
 21  gc_12      21547 non-null  float64
 22  ingtoth    21547 non-null  float64
 23  decgaphr   21547 non-null  int64
 24  decgapht   21547 non-null  int64
 25  hacina     21547 non-null  float64
 26  ch07       21547 non-null  int64
 27  ch09       21547 non-null  int64
 28  ch14       21425 non-null  float64
 29  ch15       21547 non-null  int64
 30  ch21       21547 non-null  int64
 31  regten     21547 non-null  int64
 32  propauto   21547 non-null  int64
dtypes: float64(18), int64(15)
memory usage: 5.4 MB

### Carga de la base hogares `engho2018_personas.txt`

In [5]:
personas_df = pd.read_csv(
    "../data/engho2018_personas.txt",
    sep="|",
    decimal=".",
    quotechar="\"",
    low_memory=False
)
personas_df.info()
personas_df.tail()

<class 'pandas.DataFrame'>
RangeIndex: 68725 entries, 0 to 68724
Columns: 158 entries, id to iautoconsumo_imp
dtypes: float64(97), int64(57), str(4)
memory usage: 82.8 MB

,id,provincia,miembro,pondera,region,subregion,anio,trimestre,cp03,cp04,...,ibecaspub_imp,iotrosps,m_iotrosps,iotrosps_imp,itransfermon,m_itransfermon,itransfermon_imp,iautoconsumo,m_iautoconsumo,iautoconsumo_imp
68720,127611813,94,2,68,6,6B,2018,2,31,2,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
68721,127611813,94,3,68,6,6B,2018,2,30,9,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
68722,37138480,94,1,59,6,6B,2018,2,57,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
68723,37138480,94,2,59,6,6B,2018,2,58,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68724,37138480,94,3,59,6,6B,2018,2,28,3,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0

In [6]:
personas_cols = [
    "id",           # Clave de identificación del hogar
    "miembro",      # N° de miembro en el hogar
    "pondera",      # Factor de expansión
    "cp03",         # Edad
    "cp04",         # Relación de parentesco con el jefe o la jefa del hogar
    "cp13",         # Sexo
    "region",       # Código de región
    "subregion",    # Código de subregión
    "provincia",    # Código de jurisdicción
    "niveled",      # Nivel educativo
    "cp23_08",      # ¿No cuenta con cobertura médica? 1: No, 2: Sí
    "cat_ocup",     # Categoría ocupacional (EPH)
    "rama_op",      # Rama de actividad de la ocupación principal (CAES)
    "rama_op_2",    # Rama de actividad de la ocupación principal (CAES - letra)
    "cp49",         # ¿Cuántas personas trabajan en ese establecimiento?
    "cp53",         # ¿Cuántas personas trabajan en ese establecimiento?
    "np50"          # En esta ocupación, ¿cuántas horas trabaja habitualmente por semana?
]

In [7]:
pers = personas_df[personas_cols].copy()
pers.info()

<class 'pandas.DataFrame'>
RangeIndex: 68725 entries, 0 to 68724
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         68725 non-null  int64
 1   miembro    68725 non-null  int64
 2   pondera    68725 non-null  int64
 3   cp03       68725 non-null  int64
 4   cp04       68725 non-null  int64
 5   cp13       68725 non-null  int64
 6   region     68725 non-null  int64
 7   subregion  68725 non-null  str
 8   provincia  68725 non-null  int64
 9   niveled    68725 non-null  int64
 10  cp23_08    68725 non-null  int64
 11  cat_ocup   28045 non-null  float64
 12  rama_op    28039 non-null  str
 13  rama_op_2  28034 non-null  str
 14  cp49       28042 non-null  float64
 15  cp53       2310 non-null   float64
 16  np50       2309 non-null   float64
dtypes: float64(4), int64(10), str(3)
memory usage: 8.9 MB

# Análisis exploratorio

In [9]:
hog.head()

,id,pondera,jniveled,jocupengh,cantmiem,cv1c04,cantping,reldep,regten,gastot,...,decgaphr,decgapht,hacina,ch07,ch09,ch14,ch15,ch21,regten,propauto
0,478229345,276,4,NaN,2,4,2,1.0,1,36754.0700,...,9,9,0.5,1,1,1.0,1,1,1,2
1,824935596,271,6,NaN,2,4,1,2.0,1,30000.7000,...,8,9,0.4,1,1,1.0,1,1,1,1
2,549385244,264,5,NaN,1,4,1,1.0,2,5816.0773,...,4,5,1.0,1,1,1.0,1,1,2,1
3,64338930,245,5,NaN,1,4,1,1.0,2,33049.6100,...,10,10,1.0,1,1,1.0,1,1,2,1
4,635779227,283,5,1.0,2,4,2,1.0,2,34307.2450,...,9,9,2.0,1,1,1.0,5,1,2,1

In [8]:
pers.head()

,id,miembro,pondera,cp03,cp04,cp13,region,subregion,provincia,niveled,cp23_08,cat_ocup,rama_op,rama_op_2,cp49,cp53,np50
0,478229345,1,276,83,1,1,1,1A,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN
1,478229345,2,276,82,2,2,1,1A,2,5,2,NaN,NaN,NaN,NaN,NaN,NaN
2,824935596,1,271,75,1,2,1,1A,2,6,2,NaN,NaN,NaN,NaN,NaN,NaN
3,824935596,2,271,51,3,2,1,1A,2,6,2,NaN,NaN,NaN,NaN,NaN,NaN
4,549385244,1,264,19,1,1,1,1A,2,5,1,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
hog[["cantping"]].describe()

           cantping
count  21547.000000
mean       1.935119
std        0.950050
min        0.000000
25%        1.000000
50%        2.000000
75%        2.000000
max       11.000000

In [13]:
pers[["cp49", "cp53"]].describe()

               cp49         cp53
count  28042.000000  2310.000000
mean       6.822552     5.918615
std       19.283841    18.161499
min        1.000000     1.000000
25%        1.000000     1.000000
50%        2.000000     2.000000
75%        4.000000     4.000000
max       99.000000    99.000000